//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.23 at 11:00:20 AM BRT 
//


package com.alineservices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.alineservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.alineservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetOneResponse }
     * 
     */
    public SetOneResponse createSetOneResponse() {
        return new SetOneResponse();
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link GetOneRequest }
     * 
     */
    public GetOneRequest createGetOneRequest() {
        return new GetOneRequest();
    }

    /**
     * Create an instance of {@link DeleteOneRequest }
     * 
     */
    public DeleteOneRequest createDeleteOneRequest() {
        return new DeleteOneRequest();
    }

    /**
     * Create an instance of {@link SetOneRequest }
     * 
     */
    public SetOneRequest createSetOneRequest() {
        return new SetOneRequest();
    }

    /**
     * Create an instance of {@link DeleteOneResponse }
     * 
     */
    public DeleteOneResponse createDeleteOneResponse() {
        return new DeleteOneResponse();
    }

    /**
     * Create an instance of {@link GetOneResponse }
     * 
     */
    public GetOneResponse createGetOneResponse() {
        return new GetOneResponse();
    }

}
